import {test} from 'node:test';
import assert from 'node:assert/strict';
import {JSDOM} from 'jsdom';
import {readFileSync} from 'node:fs';
const dom=new JSDOM('<main></main>',{url:'https://ducky.test/en/app/'});
for(const k of ['window','document','Node','location','history'])globalThis[k]=dom.window[k];
document.documentElement.lang='en';document.documentElement.dataset.lang='en';
let narrow=true;window.matchMedia=()=>({matches:narrow});
const copy=JSON.parse(readFileSync('i18n/en.json'));
const strings=document.createElement('script');strings.id='ducky-strings';strings.textContent=JSON.stringify(Object.fromEntries(Object.entries(copy).filter(([k])=>k.startsWith('app.')).map(([k,v])=>[k.slice(4),v])));document.body.append(strings);
const store=await import('../public/js/app/store.js');
const calendar=await import('../public/js/app/views/calendar.js');
const {closeModal}=await import('../public/js/app/ui.js');
const date=new Intl.DateTimeFormat('en-CA',{timeZone:'America/New_York',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());
const events=Array.from({length:8},(_,i)=>({date,type:i%2?'earnings':'macro',title:'Event '+i,title_en:'Event '+i,tickers:i%2?[i===1?'NVDA':'MSFT']:[],note_en:'Complete event detail '+i}));
globalThis.fetch=async url=>new Response(JSON.stringify({events:String(url).startsWith('/calendar.json')?[]:events}),{headers:{'content-type':'application/json'}});
store.set('me',{tier:'pro'});store.set('watchlist',['NVDA']);
const button=(root,label)=>[...root.querySelectorAll('button')].find(x=>x.textContent===label);
test('mobile starts with two weeks and preserves all events through list, month and filters',async()=>{
 const root=document.createElement('div');document.body.append(root);await calendar.mount(root);
 assert.equal(button(root,copy['app.calendar.mode_biweekly']).getAttribute('aria-pressed'),'true');
 assert.equal(root.querySelectorAll('.cal-ev').length,0,'grid keeps event details out of the reading flow');
 button(root,copy['app.calendar.mode_month']).click();
 const day=root.querySelector(`button[aria-label^="${date},"]`);assert.ok(day);day.click();
 assert.equal(document.querySelectorAll('#modal .cal-ev').length,8);
 closeModal();
 assert.equal(day.querySelector('.cal-event-count').textContent,'8');
 const mine=root.querySelector('.cal-mine');assert.ok(mine);mine.click();
 root.querySelector(`button[data-date="${date}"]`).click();
 assert.equal(document.querySelectorAll('#modal .cal-ev').length,5,'macro remains; only untracked earnings removed');
 closeModal();
 button(root,copy['app.calendar.mode_list']).click();
 assert.equal(root.querySelectorAll('.cal-ev').length,5);root.remove();
});
test('desktop defaults to two weeks, pages fourteen days and keeps detail inside the period',async()=>{
 narrow=false;const root=document.createElement('div');await calendar.mount(root);
 assert.equal(button(root,copy['app.calendar.mode_biweekly']).getAttribute('aria-pressed'),'true');
 button(root,copy['app.calendar.mode_biweekly']).click();
 assert.equal(root.querySelectorAll('.cal-bicell').length,14);
 assert.deepEqual([...root.querySelectorAll('.cal-biweek')].map(w=>w.querySelectorAll('.cal-bicell').length),[7,7]);
 const active=root.querySelector(`[data-date="${date}"]`);
 assert.ok(active.querySelector('.cal-biweekday').textContent);
 assert.equal(active.querySelectorAll('.pill').length,2);
 assert.equal(active.querySelector('.pill-more').textContent,'+6 more');
 active.click();
 assert.equal(document.querySelectorAll('#modal .cal-ev').length,8,'two previews still open every event');
 assert.equal(active.querySelector('.pill-kind').textContent,'Macro');
 assert.equal(document.querySelector('#modal .cal-t-macro .cal-event-brief').textContent,copy['app.event.hint_other']);
 closeModal();
 const first=root.querySelector('.cal-bicell').dataset.date;
 button(root,copy['app.calendar.jump_today']).click();
 root.querySelector(`[aria-label="${copy['app.calendar.next']}"]`).click();
 const next=root.querySelector('.cal-bicell').dataset.date;
 assert.equal((new Date(next+'T12:00:00Z')-new Date(first+'T12:00:00Z'))/86400000,14);
 assert.equal(root.querySelector('.cal-bicell[aria-pressed="true"]').dataset.date,next);
 assert.equal(root.querySelectorAll('.cal-ev').length,0,'previous-period detail is removed');
 root.querySelector(`[aria-label="${copy['app.calendar.previous']}"]`).click();
 assert.equal(root.querySelector('.cal-bicell').dataset.date,first);
 button(root,copy['app.calendar.mode_list']).click();
 assert.equal(root.querySelectorAll('.cal-ev').length,8);
 root.replaceChildren();
 await calendar.mount(root);
 assert.equal(button(root,copy['app.calendar.mode_biweekly']).getAttribute('aria-pressed'),'true','a fresh mount resets a previous list selection');
});

test('holiday survives category filters and never requests private event research',async()=>{
 const sessionDoc=JSON.parse(readFileSync('public/market-sessions.json'));
 const holiday={...sessionDoc.events.find(e=>e.date==='2026-09-07'),date};
 let researchCalls=0;
 globalThis.fetch=async url=>{if(String(url).includes('/calendar/context'))researchCalls++;return new Response(JSON.stringify({events:[holiday]}));};
 const root=document.createElement('div');document.body.append(root);await calendar.mount(root);
 button(root,copy['app.calendar.mode_list']).click();
 assert.match(root.querySelector('.cal-t-holiday').textContent,/US markets closed/);
 button(root,copy['app.calendar.f_earnings']).click();
 assert.ok(root.querySelector('.cal-t-holiday'));
 assert.match(root.querySelector('.cal-session-impact').textContent,/Theta/);
 assert.match(root.querySelector('.cal-session-impact').textContent,/not a reliable measure/);
 assert.equal(researchCalls,0);
 button(root,copy['app.calendar.mode_month']).click();
 assert.ok(root.querySelector('.cal-closed'));
 button(root,copy['app.calendar.mode_biweekly']).click();
 assert.match(root.querySelector('.cal-closed .pill').textContent,/Closed/);
 assert.match(root.querySelector('.cal-closed').getAttribute('aria-label'),/US markets closed/);
 root.remove();
});

test('month navigation and view changes keep the selected detail in the visible range',async()=>{
 const root=document.createElement('div');await calendar.mount(root);
 button(root,copy['app.calendar.mode_month']).click();
 root.querySelector(`[aria-label="${copy['app.calendar.next']}"]`).click();
 const selected=root.querySelector('.cal-cell[aria-pressed="true"]');
 assert.ok(selected);assert.equal(selected.querySelector('.cal-dnum').textContent,'1');
 const selectedDate=selected.getAttribute('aria-label').split(',')[0];
 button(root,copy['app.calendar.mode_biweekly']).click();
 assert.equal(root.querySelector('.cal-bicell[aria-pressed="true"]').dataset.date,selectedDate);
});

test('official index deep links select the effective date and survive rebalance filtering without private access',async()=>{
 const day='2026-09-21',calls=[];
 const official={id:'index:BE:add',event_id:'index:BE:add',type:'index_change',date:day,title:'BE 纳入 S&P 500',title_en:'BE joins S&P 500',tickers:['BE'],action:'add',index_name:'S&P 500',time:'盘前',time_en:'Before market open',effective_at:day,time_zone:'America/New_York',source_url:'https://example.test/official'};
 globalThis.fetch=async url=>{calls.push(String(url));return new Response(JSON.stringify({events:String(url).startsWith('/calendar.json')?[]:[official]}),{headers:{'content-type':'application/json'}});};
 store.set('me',{tier:'free'});location.hash='#/calendar?ticker=BE&date='+day;
 const root=document.createElement('div');document.body.append(root);const cleanup=await calendar.mount(root);
 try{
  assert.equal(root.querySelector('.cal-bicell[aria-pressed="true"]').dataset.date,day);
  button(root,copy['app.calendar.f_rebal']).click();
  root.querySelector(`button[data-date="${day}"]`).click();
  const row=document.querySelector('#modal .cal-t-rebal');assert.ok(row);assert.match(row.textContent,/Added to S&P 500/);assert.match(row.textContent,/Before market open · ET/);
  assert.ok(row.querySelector('a[href="https://example.test/official"]'));
  const more=row.querySelector('.cal-research-more');more.open=true;more.dispatchEvent(new window.Event('toggle'));
  assert.equal(calls.some(url=>url.includes('/calendar/context')||url.includes('/calendar/links')),false);
  assert.ok(more.querySelector('a[href="#/billing"]'));
  closeModal();
  button(root,copy['app.calendar.mode_month']).click();assert.ok(root.querySelector('.cal-sel .mbar'));
 }finally{cleanup();root.remove();location.hash='';store.set('me',{tier:'pro'});}
});
