const p=new URLSearchParams(location.search),lang=document.documentElement.dataset.lang,theme=p.get('theme')||'light';
document.documentElement.dataset.theme=theme;
window.DUCKY={API_BASE:'',BOT:'',MINIAPP:'app'};
localStorage.clear();
const raw=await (await fetch('/source.json')).json(),base={...raw,payload:undefined,id:301,extra:{...raw.payload,source_published_at:raw.published_at},ts:raw.published_at,observed_at:raw.payload.observed_at,issuer_name:'Bloom Energy',provenance:'historical_backfill'};
const records=[base,{...base,id:302,ticker:'FIX',issuer_name:'Fixture company',summary:'测试：移出指数',extra:{...base.extra,action:'remove',summary_en:'Fixture: index removal',effective_session:'unspecified'}},{id:303,kind:'news',ticker:'BE',issuer_name:'Bloom Energy',summary:'测试：公司新闻，发布时间未知',ts:'2026-09-06T12:00:00Z',observed_at:'2026-09-06T12:00:00Z',provenance:'live',extra:{event_type:'issuer_news',message_text:'测试公司新闻',message_en:'Fixture company news',summary_en:'Fixture company news; publication unknown',publication_basis:'first_observed',source_published_at:null}}];
const event={id:raw.id,event_id:raw.id,type:'index_change',date:raw.payload.effective_at,title:'BE 纳入 S&P 500',title_en:'BE joins S&P 500',tickers:['BE'],action:'add',index_name:'S&P 500',time:'盘前',time_en:'Before market open',effective_at:raw.payload.effective_at,effective_session:'before_open',effective_timezone:'America/New_York',source_url:raw.source_url};
const tickers=p.get('names')==='real'?'BE NVDA INTC GLW MSFT AAPL GOOGL AMZN META TSLA AVGO ORCL AMD QCOM TXN MU AMAT LRCX KLAC ASML ADI ARM MRVL ALAB CRDO PLTR SNOW NET DDOG CRM NOW ADBE SHOP UBER ABNB BKNG ROKU NFLX SPOT PYPL COIN HOOD COST WMT TGT LOW DELL HPE SMCI AMKR'.split(' '):['BE','NVDA','INTC','GLW',...Array.from({length:46},(_,i)=>'T'+i)],items=tickers.map((ticker,i)=>({ticker,company:i===0?'Bloom Energy':'Fixture company '+i,market_cap:p.get('caps')==='close'?1e10*(1-i/250):(51-i)*1e9,market_cap_status:'ready',market_cap_currency:'USD',market_cap_as_of:'2026-09-07T00:00:00Z',price:100,change_pct:i===49?null:(i-25)/2,price_status:i===49?'missing':'ready'}));
window.fixtureCalls=[];window.fixtureErrors=[];
window.addEventListener('error',e=>window.fixtureErrors.push(String(e.message)));window.addEventListener('unhandledrejection',e=>window.fixtureErrors.push(String(e.reason)));
const response=(body,status=200)=>new Response(JSON.stringify(body),{status,headers:{'content-type':'application/json'}});
window.fetch=async(input,opts={})=>{
 const url=new URL(String(input),location.origin),method=opts.method||'GET';window.fixtureCalls.push({path:url.pathname,query:url.search,method});
 if(method!=='GET'||url.origin!==location.origin)throw Error('Fixture rejects writes and remote requests');
 if(url.pathname.includes('archive.json'))return response({items:records.filter(r=>!url.searchParams.get('kind')||url.searchParams.get('kind').split(',').includes(r.kind)),filter_version:3,next_cursor:null});
 if(url.pathname==='/public/calendar.json')return response({events:[event],partial:false});
 if(url.pathname==='/calendar.json')return response({events:[]});
 if(url.pathname==='/calendar/links')return response({issuers:{}});
 if(url.pathname==='/calendar/context')return response({relations:[],history:{samples:[],summary:{}},selected:'BE'});
 if(url.pathname==='/watchlist')return response({items,overview:{items,session:'2026-09-04',previous_session:'2026-09-03'}});
 if(url.pathname.startsWith('/snapshot'))return response({snapshot:{ok:false}});
 if(url.pathname==='/signals/inbox')return response({items:['sent','queued','failed','cancelled','unknown'].map((status,i)=>({id:i+1,ticker:'BE',kind:i===1?'news':'index',title:i===1?'公司新闻':'BE 纳入 S&P 500',title_en:i===1?'Company news':'BE joins S&P 500',source_url:raw.source_url,published_at:i===1?null:raw.published_at,observed_at:raw.payload.observed_at,queued_at:raw.payload.observed_at,effective_at:raw.payload.effective_at,content_status:i===3?'superseded':i===4?'unavailable':'current',delivery:{status}})),next_cursor:null});
 if(url.pathname==='/creator-notifications/options')return response({tickers:items,sectors:[],push_enabled:false});
 if(url.pathname==='/creator-notifications/topics')return response({topics:[]});
 if(url.pathname==='/creator-notifications/inbox')return response({items:[],unread_count:0,next_cursor:null});
 if(url.pathname.includes('seasonality'))return response({rows:[],as_of:'2026-09-04'});
 return response({items:[],sources:[],sectors:[],status:'unavailable'});
};
const store=await import('/js/app/store.js');store.set('me',{id:900001,tier:p.get('tier')||'pro',watch_cap:50});store.set('watchlist',tickers);store.set('snapshots',{});
const view=p.get('view')||'boards';location.hash=view==='calendar'?'#/calendar?ticker=BE&date=2026-09-21':view==='boards'?'#/boards?mode=archive':'#/'+view;
document.querySelector('.app-topbar')?.setAttribute('data-fixture','true');
const badge=document.createElement('p');badge.textContent='READ-ONLY QA FIXTURE · '+innerWidth+' px';badge.style.cssText='margin:0;text-align:center;font-size:12px;background:#fff;color:#000';document.body.prepend(badge);
const module=await import('/js/app/views/'+view+'.js');let dispose=await module.mount(document.getElementById('view'),{query:new URLSearchParams(view==='boards'?'mode=archive':'')});
window.fixtureReady=true;
const qaStatus=document.createElement('output');qaStatus.id='fixture-status';qaStatus.style.cssText='display:block;font-size:10px;color:#000;background:#fff;overflow-wrap:anywhere;max-height:48px;overflow:auto';document.body.append(qaStatus);
setInterval(()=>{qaStatus.textContent=JSON.stringify({width:innerWidth,scrollWidth:document.documentElement.scrollWidth,calls:window.fixtureCalls,errors:window.fixtureErrors});},200);
let mountedView=view;window.addEventListener('hashchange',async()=>{const next=location.hash.split('?')[0].slice(2);if(!['calendar','watchlist','boards','updates'].includes(next)||next===mountedView)return;dispose?.();mountedView=next;const root=document.getElementById('view');root.replaceChildren();root.className='app-view';const nextModule=await import('/js/app/views/'+next+'.js');dispose=await nextModule.mount(root,{query:new URLSearchParams(location.hash.split('?')[1]||'')});});
